library("rstan")
library("foreign")
library("ggmcmc")
library("jsonlite")

options(scipen = 999)
options(max.print = 100000)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

source("modules/extractSamples.R")
source("modules/generateDiagnosticPlots.R")
source("modules/fitModel.R")
source("modules/hdi.R")
source("modules/saveSamples.R")
source("modules/stanToCoda.R")
source("modules/submatrixes.R")
source("modules/summarizeSamples.R")
source("modules/zeros.R")
